// plugin/src/ui/TaskList.svelte
<script lang="ts">
  import type { TaskTree } from "../data/transformations/relationships";
  import TaskRenderer from "./TaskRenderer.svelte";

  export let taskTrees: TaskTree[];
</script>

<ul class="todoist-task-list">
  {#each taskTrees as taskTree (taskTree.id)}
    <TaskRenderer {taskTree} />
  {/each}
</ul>

// plugin/src/ui/query/task/TaskList.tsx
import { AnimatePresence } from "motion/react";
import type React from "react";

import type { TaskTree } from "@/data/transformations/relationships";
import { Task } from "@/ui/query/task/Task";

type Props = {
  trees: TaskTree[];
};

export const TaskList: React.FC<Props> = ({ trees }) => {
  return (
    <div className="todoist-tasks-list">
      <AnimatePresence>
        {trees.map((tree) => (
          <Task key={tree.id} tree={tree} />
        ))}
      </AnimatePresence>
    </div>
  );
};
